BUILD: Resync rpmbuild-docker script

diff --git a/rpmbuild-docker b/rpmbuild-docker
--- a/rpmbuild-docker
+++ b/rpmbuild-docker
@@ -102,9 +102,9 @@ while (( $# > 0 )); do
     ## --update: update repository with new packages
     --update) UPDATE=1 ;;
     ## --keep: keep build environment after build_ldflags
-    --keep) KEEP=1 ;;
+    --keep) KEEP=1; NOKEEP= ;;
     ## --nokeep: never keep build environment on error
-    --nokeep) NOKEEP=1 ;;
+    --nokeep) NOKEEP=1; KEEP= ;;
     ## --gitrev: create source0 tarball from git revision
     --gitrev) GITREV=$2 ; shift ;;
     ## --sign: enable rpm signing
@@ -211,8 +211,8 @@ if [[ -n $SIGN ]]; then
     GPG_SECRET_KEY=$(if [[ -n $GPG_PASSPHRASE_FILE ]]; then cat "$GPG_PASSPHRASE_FILE"
         else (set +x && echo "${!GPG_PASSPHRASE_ENV}"); fi |
       gpg --homedir "$GPG_HOMEDIR" --batch --passphrase-fd 0 --pinentry-mode loopback \
-        --armor --export-secret-keys --with-fingerprint "$GPG_KEYID") ||
-          fatal 'Failed to export GPG secret key'
+        --armor --export-secret-keys --with-fingerprint "$GPG_KEYID")
+    [[ $? != 0 || -z $GPG_SECRET_KEY ]] && fatal 'Failed to export GPG secret key'
   fi
 fi
 
@@ -223,6 +223,20 @@ echo "OUTPUTDIR: $OUTPUTDIR"
 echo "PREBUILDSCRIPT: ${PREBUILDSCRIPT:-none}"
 echo "REPO: ${REPO:-none}"
 echo "SIGN: ${SIGN:-0}"
+
+docker_version=$(docker --version)
+if (( $? == 127 )); then
+    fatal 'Command docker --version failed with status 127, docker/podman environment not ready!'
+elif [[ ${docker_version,,} == *podman*  ]]; then
+    IS_PODMAN=1
+    IS_DOCKER=
+else
+    IS_PODMAN=
+    IS_DOCKER=1
+fi
+
+echo "IS_DOCKER: $IS_DOCKER"
+echo "IS_PODMAN: $IS_PODMAN"
 
 # Yum might take for ages to complete because it CLOEXEC on all available
 # file descriptors and recent dockers sets a very high default limit.
@@ -304,19 +318,27 @@ function dockerfile_for_dist() {
 # normal dockerfile method may work with recent distro/docker
 DOCKER_OPTS_DIST_el9=( --security-opt seccomp=unconfined )
 function dockerscript_for_dist_el9() {
-    IMAGE=$1; shift
-    echo "# Build $IMAGE..."
-    set -xe
-    id=$(docker run "$@" -d rockylinux:9 sleep infinity)
-    docker exec "$id" dnf update -y
-    docker exec "$id" dnf install -y createrepo gcc make rpm-build
-    docker exec "$id" sh -c "echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf"
-    docker exec "$id" sh -c "echo keepcache=1 >> /etc/dnf/dnf.conf"
-    docker exec "$id" sh -c $'awk \x27/^\[/ { inside=$1 } inside=="[crb]"&&/enabled/{print "enabled=1"; next}{print}\x27 /etc/yum.repos.d/rocky.repo > /etc/yum.repos.d/rocky.repo.new && mv /etc/yum.repos.d/rocky.repo{.new,}'
-    docker exec "$id" dnf clean all
-    docker container commit "$id" "$IMAGE"
-    docker kill "$id"
-    docker rm "$id"
+  IMAGE=$1; shift
+  echo "# Build $IMAGE..."
+  set -xe
+  id=$(docker run "$@" -d ${DOCKER_HUB_IMAGE:-rockylinux:9} sleep infinity)
+  docker exec "$id" dnf update -y
+  docker exec "$id" dnf install -y createrepo gcc make rpm-build
+  docker exec "$id" sh -c "echo '* - nproc 2048' >> /etc/security/limits.d/90-nproc.conf"
+  docker exec "$id" sh -c "echo keepcache=1 >> /etc/dnf/dnf.conf"
+  docker exec "$id" sh -c $'awk \x27/^\[/ { inside=$1 } inside=="[crb]"&&/enabled/{print "enabled=1"; next}{print}\x27 /etc/yum.repos.d/rocky.repo > /etc/yum.repos.d/rocky.repo.new && mv /etc/yum.repos.d/rocky.repo{.new,}'
+  docker exec "$id" dnf clean all
+  docker container commit "$id" "$IMAGE"
+  docker kill "$id"
+  docker rm "$id"
+}
+
+# normal dockerfile method may work with recent distro/docker
+DOCKER_OPTS_DIST_el10=( --security-opt seccomp=unconfined )
+DOCKERSCRIPT_ENV_for_el10=$(declare -f dockerscript_for_dist_el9)
+function dockerscript_for_dist_el10() {
+  DOCKER_HUB_IMAGE='rockylinux/rockylinux:10' \
+    dockerscript_for_dist_el9 "$@"
 }
 
 # Lookup docker script source to build a base image for $DIST.
@@ -324,6 +346,8 @@ function dockerscript_for_dist() {
   if [[ -f ~/.config/${0##*/}/build-image.$DIST ]]; then
     cat ~/.config/"${0##*/}/build-image.$DIST"
   elif declare -f "dockerscript_for_dist_$DIST"; then
+    local env_ref="DOCKERSCRIPT_ENV_for_$DIST"
+    [[ -n ${!env_ref} ]] && echo "$DOCKERSCRIPT_ENV_for_el10"
     echo "'dockerscript_for_dist_$DIST' \"\$@\""
   else
     return 1
@@ -442,6 +466,7 @@ DOCKER_OPTS=(
   --mount "type=bind,src=$SPECDIR/$SPECFILE,dst=/tmp/$SPECFILE"
   --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/yum"
   --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/dnf"
+  --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/libdnf5"
   --mount "type=bind,src=$CACHEBASE/cache-shared,dst=/tmp/cache-shared"
   --mount "type=bind,src=$SOURCEDIR,dst=/tmp/shared/SOURCES"
   --mount "type=bind,src=$OUTPUTDIR/SRPMS,dst=/tmp/shared/SRPMS"
@@ -450,6 +475,7 @@ DOCKER_OPTS=(
   ${GPG_SECRET_KEY_FILE:+--mount "type=bind,src=$GPG_SECRET_KEY_FILE,dst=/dev/shm/k,ro"}
   ${REPO:+--mount "type=bind,src=$REPO,dst=/tmp/local-repo"}
   ${PREBUILDSCRIPT:+--mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/${PREBUILDSCRIPT##*/}"}
+  ${IS_PODMAN:+--userns keep-id --user 0}
 )
 
 function build_exit() {
@@ -487,6 +513,9 @@ function build_main() {
   chown "$BUSER:$BGROUP" "$BHOME"
 
   if [[ -n $SIGN ]]; then
+    signreq=()
+    for i in rpm-sign gnupg2; do rpm -q "$i" || signreq+=( "$i" ); done
+    [[ -n $signreq ]] && yum install -y "${signreq[@]}"
     build_runuser mkdir -m 700 /dev/shm/g
     build_runuser ln -sT /dev/shm/g "$BHOME/.gnupg"
     build_runuser sh -exc 'GPG_TTY= gpg --passphrase-file /dev/shm/.p \
@@ -547,7 +576,6 @@ EOF
   build_runuser rpmbuild "${rpmbuildopts[@]}" -ba "/tmp/$SPECFILE"
 
   if [[ -n $SIGN ]]; then
-    rpm -q rpm-sign || yum install -y rpm-sign
     rpms=( $(find /tmp/build/{RPMS,SRPMS} -type f -name '*.rpm') )
     if [[ -n $rpms ]]; then
       build_runuser sh -exc 'GPG_TTY= rpm \
@@ -573,6 +601,10 @@ trap 'docker kill "$CTNAME"; exit;' INT
 cat <<__EOF__ |docker run "${DOCKER_OPTS[@]}" "$IMAGE" /bin/bash &
 declare -p HOSTNAME
 $(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP REPO RPMOPTS RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE SIGN GPG_KEYID)
+# podman creates group/passwd entries when run with --userns keep-id,
+# but lets's normalize with docker, so reset them first
+sed -i -e "/^$BGROUP:/d" /etc/group
+sed -i -e "/^$BUSER:/d" /etc/passwd
 echo "$(getent group "$BGROUP")" >> /etc/group
 echo "$(getent passwd "$BUSER")" >> /etc/passwd
 ${GPG_SECRET_KEY:+(umask 0277 && (set +x && echo $(printf '%q\n' "$GPG_SECRET_KEY")) > /dev/shm/k && chown "\$BUSER" /dev/shm/k)}
